[build]
  base = "Fair-Game_Offical-main"   # Base directory is the subfolder containing your files
  command = "node buildComm.js"     # Make sure the build command points to the correct script
  publish = "Fair-Game_Offical-main/dist"  # The dist folder is inside the subfolder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
