[build]
  publish = "public"  # Replace "public" with the folder where your site files are located
  command = ""        # No build command needed for static sites

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
