[build]
  base = "Fair-Game_Offical/Fair-Game_Offical-main/"  # Base directory points to the subfolder containing your source files and buildComm.js
  command = "node buildComm.js"    # Run the build script from the subfolder
  publish = "Fair-Game_Offical-main/dist"  # The dist folder is inside the subfolder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
