[build]
  base = "Fair-Game_Offical-main"  # The subfolder containing your build script
  command = "node buildComm.js"    # The build command, runs in the subfolder
  publish = "Fair-Game_Offical-main/dist"  # The folder where the built files will be placed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
