[build]
  base = "Fair-Game_Offical-main"  # The subfolder that contains your build script
  command = "node buildComm.js"    # Runs the build script in the subfolder
  publish = "Fair-Game_Offical-main/dist"  # The directory where the built files will be placed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
