[build]
  base = "Fair-game_Offical-main"  # We're now in the root of 'Fair-Game_Offical-main', so base is the current directory
  command = "node buildComm.js"  # This will run the build script inside this subfolder
  publish = "dist"  # The build output will be placed in 'Fair-Game_Offical-main/dist'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
