[build]
  base = "."  # Set the base to the subfolder containing the build files
  command = "node buildComm.js"    # The build command inside the subfolder
  publish = "dist"  # The output directory (inside the subfolder)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

