[build]
  base = "Fair-Game_Offical-main"  # Set the base to the subfolder containing the build files
  command = "node buildComm.js"    # The build command inside the subfolder
  publish = "Fair-Game_Offical-main/dist"  # The output directory (inside the subfolder)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

