[settings]
repository = "Fair-Game_Offical"
entry_file = "buildComm.js"
output_dir = "dist"

[build]
command = "node buildComm.js"
publish = "dist/"
base ="Fair-Game_Offical-main/index.html"

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200
