[build]
  command = "node buildComm.js"  # Runs your build script
  publish = "dist"               # Directory for deployment
  base = "."                     # Base directory is the current directory (subfolder)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
